version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql-data/mysql:/var/lib/mysql
    ports:
      -  "3305:3305"
    user: "1000:50"
  app:
    build: .
    environment:
      PASSWORD: ${MYSQL_PASSWORD}
      DATABASE: ${MYSQL_DATABASE}
    command: rails s -p 3300 -b '0.0.0.0'
    volumes:
      - .:/dairy_dream
    ports:
      - "3300:3300"
    tty: true
    stdin_open: true
    links:
      - db
volumes: 
  mysql-data:

