version: '3'
services:
  db-data:
    container_name: mysql-data
    image: busybox
    volumes:
      - ./mysql-data/mysql:/var/lib/mysql:rw
  db:
    container_name: mysql-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes_from:
      - db-data
    ports:
      -  "3305:3305"
    user: "1000:50"
  app:
    build: .
    command: rails s -p 3300 -b '0.0.0.0'
    volumes:
      - .:/dairy_dream
    ports:
      - "3300:3300"
    tty: true
    stdin_open: true
    links:
      - db

