version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      -  "3305:3305"
  app:
    build: .
    command: rails s -p 3300 -b '0.0.0.0'
    volumes:
      - .:/dairy_dream
    ports:
      - "3300:3300"
    links:
      - db

